# Generated by Django 5.1 on 2024-08-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=20, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('person', models.ForeignKey(default='000000000000', null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
