# Generated by Django 5.1 on 2024-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
