# Generated by Django 5.1 on 2024-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bankaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
